uploads = []
outputs = []

[[generated]]
id = "6ikRG8EYS4gp_7AXon3u2"
uri = "file://artifacts/khelam/assets/images/icon.png"
type = "image"
title = "khelam_app_icon"

[[generated]]
id = "P7M7LBQzoYr_4w0PV8KMc"
uri = "file://artifacts/khelam/assets/images/futsal_banner.png"
type = "image"
title = "futsal_game_banner"

[[generated]]
id = "rqeg-wOCVGR9kZSecfPOJ"
uri = "file://artifacts/khelam/assets/images/football_banner.png"
type = "image"
title = "football_game_banner"

[[generated]]
id = "OtiRnAYUw7DFmCuXG_T7Z"
uri = "file://artifacts/khelam/assets/images/cricket_banner.png"
type = "image"
title = "cricket_game_banner"
